# Generated by Django 4.2.13 on 2024-06-18 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100)),
                ('basic_salary', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('hours', models.PositiveIntegerField(default=0)),
                ('gross_salary', models.PositiveIntegerField(default=0)),
                ('jobtitle_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MAKAPP.jobtitle')),
            ],
        ),
    ]
